console.log(typeof 91); // typeof number
console.log(typeof false); // typeof boolean
console.log(typeof "245"); // typeof string
console.log(typeof undefined); // typeof undefined
console.log(typeof null); // typeof object

//! Primitive Data Types

//* Primitive data types in JavaScript include:

//? Numbers - Integers, floats
//? Strings - Any data under single quote, double quote or backtick quote
//? Booleans - true or false value
//? Null - empty value or no value
//? Undefined - a declared variable without a value
//? Symbol - A unique value that can be generated by Symbol constructor

let word = "Javascript";
console.log(word); // Javascript

console.log(word[0]); // J

let numOne = 3;
let numTwo = 3;

console.log(numOne == numTwo); // true

let js = "Javascript";
let py = "Python";

console.log(js == py); // false

let lightOn = true;
let lightOff = false;

console.log(lightOn == lightOff); // false

//! Non-Primitive Data Types

//* Non-primitive data types in JavaScript includes:

//? Objects
//? Arrays

let nums = [1, "prototurk", 3]; //! Array

console.log(nums); // [1, 'prototurk', 3]

nums[1] = 2;

console.log(nums); // [1, 2, 3]

let nums1 = [1, 2, 3];
let nums2 = [1, 2, 3];

console.log(nums1 == nums2); // false

let userOne = {
  name: "Asabeneh",
  role: "teaching",
  country: "Finland",
};

let userTwo = {
  name: "Asabeneh",
  role: "teaching",
  country: "Finland",
};

console.log(userOne == userTwo); // false

let user1 = {
  name: "Tayfun",
  surname: "Erbilen",
};

let user2 = {
  name: "Tayfun",
  surname: "Erbilen",
};

console.log(user1 == user2); // false

let nums0 = [1, 2, 3];
let numbers = nums0;

console.log(nums0 == numbers); // true

let userOne1 = {
  name: "Asabeneh",
  role: "teaching",
  country: "Finland",
};

let userTwo2 = userOne1;

console.log(userOne1 == userTwo2); // true

//! Numbers

//* Declaring Number Data Types

let age = 35;
const gravity = 9.81; // we use const for non-changing values, gravitational constant in m/s2
let mass = 72; // mass in Kilogram
// const PI = 3.14; // pi a geometrical constant
const boilingPoint = 100; // temperature in oC, boiling point of water which is a constant
const bodyTemp = 37; // oC average human body temperature, which is a constant

console.log(age, gravity, mass, boilingPoint, bodyTemp);

//* Math Object

const PI = Math.PI;

console.log(PI); // 3.141592653589793

console.log(Math.round(5.5)); // 6
console.log(Math.ceil(5.49)); // 6
console.log(Math.floor(5.49)); // 5
console.log(Math.min(3, 5, 1, -5, -37)); // -37
console.log(Math.max(3, 5, 1, -5, -37)); // 5
console.log(Math.random()); // rastgele sayi veriyor

// let us create random number between 0 to 10

const num = Math.floor(Math.random() * 11); // creates random number between 0 nd 10
console.log(num);

// Absolut value
console.log(Math.abs(-10)); // 10

// Square root
console.log(Math.sqrt(441)); // 21
console.log(Math.sqrt(169)); // 13

//Power
console.log(Math.pow(5, 4)); // 625

let randomNum = Math.random(); // generates 0 to 0.99
let numBtnZeroAndTen = randomNum * 11;

console.log(numBtnZeroAndTen); // this gives: min 0 and max 10.99

let randomNumRoundToFloor = Math.floor(numBtnZeroAndTen);
console.log(randomNumRoundToFloor); // this gives between 0 and 10

//! Strings
//* Strings tek tirnak, cift tirnak, backtick arasinda olur.

let space = "";
let firstName = "M.Kerem";
let lastName = "Aktürkoglu";
let country = "Türkiye";
let city = "Istanbul";
let language = "Javascript";
let job = "football-player";
let quote = "Thats the football, its the football";

console.log(space, firstName, lastName, country, city, language, job, quote);

//* String Concatenation
//* Birden fazla string'leri birlestirmeye yarar.

let name = "Hakan";
let surname = "Sükür";

let fullName = name + " " + surname;
console.log(fullName); // Hakan Sükür

//* String'lerde Kacis (Escape) Dizeleri

// \n: new line
// \t: Tab, means 8 spaces
// \\: Back slash
// \': Single quote(')
// \'': Double quote('')

let paragragh = "benim\nadim\nkazim\nakyol";
console.log(paragragh);

//* Template Strings (``) (Backtick)

//Syntax
// `String literal text`
// `String literal text ${expression}`

let fullName1 = `${name} ${surname}`;
console.log(fullName1); // Hakan Sükür

let a = 2;
let b = 3;
console.log(`${a} is greater than ${b}: ${a > b}`); // 2 is greater than 3 : false

//! String Methods

//* Everything in JavaScript is an object.

//? 1.lenght: uzunluk

let youtube = "prototurk";
console.log(youtube.length); // 9 karakter

//? 2.Bir dize içindeki karakterlere erişme: Bir dizedeki her karaktere indeksini kullanarak erişebiliriz. Programlamada sayma 0'dan başlar. Dizenin ilk indeksi sıfırdır ve son indeks dizenin uzunluğu eksi birdir.

let lastIndex = youtube.length - 1;
console.log(youtube[lastIndex]); // k

//? 3.toUpperCase(): this method changes the string to uppercase letters. (büyük harfe cevirir)

let dizi = "prototurk";
console.log(dizi.toUpperCase()); // PROTOTURK

let string = "JavaScript";
console.log(string.toUpperCase()); // JAVASCRIPT

let country0 = "Deutschland";
console.log(country0.toUpperCase()); // DEUTSCHLAND

//? 4.toLowerCase(): this method changes the string to lowercase letters. (kücük harfe cevirir)

let dizi0 = "AKADEMI";
console.log(dizi0.toLowerCase()); // akademi

let string0 = "JAVASCRIPT";
console.log(string0.toLowerCase()); // javascript

let country1 = "UNITED STATES OF AMERICA";
console.log(country1.toLowerCase()); // united states of america

//? 5.substr(): Başlangıç dizini ve dilimlenecek karakter sayısı olmak üzere iki bağımsız değişken alır.

let neu = "TypeScript";
console.log(neu.substr(4, 6)); // Script

let team = "ManchesterCity";
console.log(team.substr(10, 4)); // City

//? 6.substring(): 
