console.log(typeof 91); // typeof number
console.log(typeof false); // typeof boolean
console.log(typeof "245"); // typeof string
console.log(typeof undefined); // typeof undefined
console.log(typeof null); // typeof object

//! Primitive Data Types

//* Primitive data types in JavaScript include:

//? Numbers - Integers, floats
//? Strings - Any data under single quote, double quote or backtick quote
//? Booleans - true or false value
//? Null - empty value or no value
//? Undefined - a declared variable without a value
//? Symbol - A unique value that can be generated by Symbol constructor

let word = "Javascript";
console.log(word); // Javascript

console.log(word[0]); // J

let numOne = 3;
let numTwo = 3;

console.log(numOne == numTwo); // true

let js = "Javascript";
let py = "Python";

console.log(js == py); // false

let lightOn = true;
let lightOff = false;

console.log(lightOn == lightOff); // false

//! Non-Primitive Data Types

//* Non-primitive data types in JavaScript includes:

//? Objects
//? Arrays

let nums = [1, "prototurk", 3]; //! Array

console.log(nums); // [1, 'prototurk', 3]

nums[1] = 2;

console.log(nums); // [1, 2, 3]

let nums1 = [1, 2, 3];
let nums2 = [1, 2, 3];

console.log(nums1 == nums2); // false

let userOne = {
  name: "Asabeneh",
  role: "teaching",
  country: "Finland",
};

let userTwo = {
  name: "Asabeneh",
  role: "teaching",
  country: "Finland",
};

console.log(userOne == userTwo); // false

let user1 = {
  name: "Tayfun",
  surname: "Erbilen",
};

let user2 = {
  name: "Tayfun",
  surname: "Erbilen",
};

console.log(user1 == user2); // false

let nums0 = [1, 2, 3];
let numbers = nums0;

console.log(nums0 == numbers); // true

let userOne1 = {
  name: "Asabeneh",
  role: "teaching",
  country: "Finland",
};

let userTwo2 = userOne1;

console.log(userOne1 == userTwo2); // true

//! Numbers

//* Declaring Number Data Types

let age = 35;
const gravity = 9.81; // we use const for non-changing values, gravitational constant in m/s2
let mass = 72; // mass in Kilogram
// const PI = 3.14; // pi a geometrical constant
const boilingPoint = 100; // temperature in oC, boiling point of water which is a constant
const bodyTemp = 37; // oC average human body temperature, which is a constant

console.log(age, gravity, mass, boilingPoint, bodyTemp);

//* Math Object

const PI = Math.PI;

console.log(PI); // 3.141592653589793

console.log(Math.round(5.5)); // 6
console.log(Math.ceil(5.49)); // 6
console.log(Math.floor(5.49)); // 5
console.log(Math.min(3, 5, 1, -5, -37)); // -37
console.log(Math.max(3, 5, 1, -5, -37)); // 5
console.log(Math.random()); // rastgele sayi veriyor

// let us create random number between 0 to 10

const num = Math.floor(Math.random() * 11); // creates random number between 0 nd 10
console.log(num);

